language: python
python: 
- "3.6"
install:
  - pip3 install -r requirements.txt
  
before_script:
    - sudo redis-server /etc/redis/redis.conf --port 6379 --hostname redis_server

script:
  - cd program
  - pytest
